"""One schema writer, which prunes what otto no longer emits (#498)."""

import json
from pathlib import Path

from otto.models.jsonschema import build_schemas, schema_drift, write_schemas


def _otto_schemas(tmp_path: Path) -> Path:
    out = tmp_path / ".otto" / "schemas"
    out.mkdir(parents=True)
    return out


def test_every_built_document_is_written(tmp_path: Path) -> None:
    out = tmp_path / "out"
    result = write_schemas(out)
    assert sorted(p.name for p in result.written) == sorted(
        f"{s}.schema.json" for s in build_schemas()
    )
    assert result.pruned == []


def test_in_otto_schemas_every_orphan_is_pruned_and_drift_clears(tmp_path: Path) -> None:
    out = _otto_schemas(tmp_path)
    orphan = out / "retired-host.schema.json"
    orphan.write_text("{}")  # unstamped: still otto's, this directory is otto-owned
    assert any("orphaned" in p for p in schema_drift(out))
    result = write_schemas(out)
    assert result.pruned == [orphan]
    assert not orphan.exists()
    assert schema_drift(out) == []


def test_in_a_foreign_directory_only_stamped_orphans_are_pruned(tmp_path: Path) -> None:
    out = tmp_path / "mine"
    out.mkdir()
    users = out / "users-own.schema.json"
    users.write_text(json.dumps({"title": "not otto's"}))
    stamped = out / "retired-host.schema.json"
    stamped.write_text(json.dumps({"x-otto-version": "0.0.1"}))
    result = write_schemas(out)
    assert result.pruned == [stamped]
    assert users.exists()


def test_non_schema_files_and_odd_shapes_are_never_touched(tmp_path: Path) -> None:
    out = _otto_schemas(tmp_path)
    keep = [out / "README.md", out / "notes.json"]
    for path in keep:
        path.write_text("{}")
    (out / "dir.schema.json").mkdir()
    write_schemas(out)
    assert all(p.exists() for p in keep)
    assert (out / "dir.schema.json").is_dir()
    foreign = tmp_path / "foreign"
    foreign.mkdir()
    listy = foreign / "listy.schema.json"
    listy.write_text(json.dumps(["x-otto-version"]))
    garbage = foreign / "garbage.schema.json"
    garbage.write_text("{not json")
    assert write_schemas(foreign).pruned == []
    assert listy.exists()
    assert garbage.exists()


def test_drift_reports_missing_stale_unparsable_and_orphaned(tmp_path: Path) -> None:
    out = _otto_schemas(tmp_path)
    write_schemas(out)
    (out / "lab.schema.json").unlink()
    (out / "settings.schema.json").write_text(json.dumps({"x-otto-version": "0.0.1"}))
    (out / "link.schema.json").write_text("{nope")
    (out / "extra.schema.json").write_text("{}")
    text = "\n".join(schema_drift(out))
    for word in ("missing", "generated by otto 0.0.1", "unparsable", "orphaned"):
        assert word in text, word
    assert "re-run `otto init --schemas` or `otto schema export`" in text


def test_drift_survives_a_non_utf8_schema_file(tmp_path: Path) -> None:
    out = _otto_schemas(tmp_path)
    write_schemas(out)
    (out / "lab.schema.json").write_bytes(b"\xff")
    problems = schema_drift(out)
    assert any("lab.schema.json: unparsable" in p for p in problems)


def test_drift_does_not_report_a_directory_the_writer_cannot_prune(tmp_path: Path) -> None:
    out = _otto_schemas(tmp_path)
    write_schemas(out)
    (out / "dir.schema.json").mkdir()
    assert schema_drift(out) == []


def test_builtins_only_in_otto_schemas_prunes_a_custom_host_types_schema(tmp_path: Path) -> None:
    from otto.host.os_profile import register_host_class
    from otto.host.unix_host import UnixHost
    from otto.models.host import UnixHostSpec

    class PinnedHost(UnixHost):
        pass

    class PinnedHostSpec(UnixHostSpec):
        pass

    register_host_class(
        "pinnedos", PinnedHost, spec=PinnedHostSpec
    )  # the root guard restores the registries
    out = _otto_schemas(tmp_path)
    custom = out / "pinned-host.schema.json"
    assert custom in write_schemas(out).written
    result = write_schemas(out, builtins_only=True)
    assert result.pruned == [custom]
    assert not custom.exists()
