"""Render ``src/otto/check/proven.json`` into ``docs/cli/link/known-good.md``.

Run from the repo root::

    uv run python -m scripts.render_proven_range           # write the page
    uv run python -m scripts.render_proven_range --check   # render, write nothing

``proven.json`` is the single home for the environments otto has proven its
link features on: ``otto link check`` labels each host against it, and this
page is how a reader sees it. ``docs/conf.py`` runs this at
``builder-inited`` for every builder; the page is git-ignored, so the only
copy in the tree is the data file itself.
"""

import argparse
import sys
from pathlib import Path

from otto.check.proven import ORDERED_COMPONENTS, ProvenRange, load_proven_range

ISSUES_URL = "https://github.com/ludachrish3/otto-sh/issues"

PAGE_PATH = Path(__file__).resolve().parent.parent / "docs" / "cli" / "link" / "known-good.md"

LINK_CHECK_COMPONENTS = ["iproute2", "kernel", "isa", "userland"]
"""The components ``otto link check`` labels on every host it fingerprints."""

WHAT = {
    "iproute2": "The iproute2 release `tc -V` reports (`ss170501`-style or dotted)",
    "kernel": "The kernel release, as `uname -r` prints it",
    "isa": "The machine architecture, as `uname -m` prints it",
    "userland": "`gnu`, or `busybox` when a tool the check uses is a BusyBox applet",
    "socat": "The socat version",
    "bash": "The bash version",
    "launcher": "How a detached process is started (`systemd-run --user`, or `setsid`)",
}
"""What each component's version column holds, in the reader's terms."""


def _esc(text: str) -> str:
    """Escape what a Markdown table cell cannot hold literally."""
    return text.replace("|", "\\|").replace("\n", " ")


def _component(name: str, proven: ProvenRange) -> "list[str]":
    """One component's heading, one-line description and table (or the empty note)."""
    entries = proven.components[name]
    compared = (
        "Compared by version order: a host reads `within`, `older` or `newer`."
        if name in ORDERED_COMPONENTS
        else "Compared by exact match: a host reads `within` or `outside`."
    )
    what = WHAT.get(name)
    labeled = name in LINK_CHECK_COMPONENTS
    lines = [f"## {name}", "", *([f"{what}."] if what else []), *([compared] if labeled else [])]
    lines.append("")
    if not entries and labeled:
        lines += [
            "Not yet proven: `otto link check` labels this component, but no bed run has",
            "recorded a version here, so every host it fingerprints reads `unknown` for",
            "this component.",
            "",
        ]
        return lines
    if not entries:
        lines += [
            "Not yet proven: no bed run has recorded a version here. `otto link check`",
            "does not label this component, so no link check reads it.",
            "",
        ]
        return lines
    lines += ["| version | where | when |", "|---|---|---|"]
    lines += [f"| `{_esc(e.version)}` | {_esc(e.where)} | {_esc(e.when)} |" for e in entries]
    lines.append("")
    return lines


def render(proven: "ProvenRange | None" = None) -> str:
    """Compose the whole page, as Markdown."""
    proven = proven if proven is not None else load_proven_range()
    link_names = ", ".join(f"`{n}`" for n in LINK_CHECK_COMPONENTS)
    other = [n for n in proven.components if n not in LINK_CHECK_COMPONENTS]
    lines = [
        "# Known-good environments",
        "",
        (
            "<!-- GENERATED by scripts/render_proven_range.py from"
            " src/otto/check/proven.json; do not edit -->"
        ),
        "",
        "The versions otto has proven its link features on, component by component, with",
        "where and when each was proven. Rows come only from otto's own bed runs.",
        "[`otto link check`](check.md) compares every host it fingerprints against this list",
        "and prints the result on its `proven range:` line; the labels it uses are defined",
        "in [proven-range labels](../check-verdicts.md#proven-range-labels).",
        "",
        "Outside the range is not the same as broken. It means otto has no evidence",
        "either way for your version, and your check result is that evidence.",
        "",
        f"`otto link check` labels {link_names}.",
    ]
    if other:
        names = ", ".join(f"`{n}`" for n in other)
        lines.append(f"{names} are recorded for the planned `otto tunnel check`.")
    lines += [
        f"This page was generated from revision `{proven.revision}` of the list. A",
        "component with no table is not yet proven on any version.",
        "",
    ]
    for name in proven.components:
        lines += _component(name, proven)
    lines += [
        "## Sending a report",
        "",
        "Any report is welcome. One is most useful when a host reads `older`, `newer`",
        "or `outside` on its `proven range:` line, or when any row isn't `pass`: run",
        "`otto link check <link> --report check.json` against it and attach `check.json`",
        f"to [an issue]({ISSUES_URL}). A passing report from outside the range is how a",
        "new version joins this page (once otto reproduces it on its own bed); a failing",
        "one is a bug report with the evidence already attached. `unknown` alone is",
        "common and needs no report: it often just means otto has nothing recorded for",
        "that component yet.",
        "What the file holds, and what to redact, is on",
        "[the verdicts page](../check-verdicts.md#the-report-file).",
        "",
    ]
    return "\n".join(lines)


def main(argv: "list[str]") -> int:
    """Render the page, or render it and write nothing."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", type=Path, default=PAGE_PATH)
    parser.add_argument("--check", action="store_true", help="render only; write nothing")
    args = parser.parse_args(argv)
    page = render()
    if args.check:
        print(f"proven range: renders ({len(page.splitlines())} lines)")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(page, encoding="utf-8")
    print(f"proven range: wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
